# Generated by Django 3.0 on 2021-04-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImages',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('type', models.CharField(db_index=True, max_length=50)),
                ('aws_path', models.CharField(db_index=True, max_length=450)),
                ('size', models.CharField(db_index=True, max_length=100)),
                ('last_modified', models.CharField(db_index=True, max_length=300)),
                ('end_point', models.CharField(db_index=True, max_length=100)),
            ],
        ),
    ]
