# Generated by Django 3.0 on 2021-04-21 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buttons_screen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimages',
            name='last_modified',
        ),
    ]
