# Generated by Django 3.0 on 2021-04-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttons_screen', '0002_remove_uploadedimages_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimages',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
